version: "3.7"

services:
  voter-app:
    build: .
    ports:
      - 3000:3000
    environment:
      MONGO_URI: mongodb://mongodb-myapp:27017/

  mongodb-myapp:
     image: mongo
     ports:
       - "27017:27017"
     volumes:
      - voterAppDb:/data/db

volumes:
    voterAppDb:
        external: false